### ISSUE TITLE
Automatic Scan Fail

### ISSUE THREAD

**Issue by vsoch** [autamus/spacktainer-registry#5]
@alecbcs you probably got the notification, but our automatic check failed and it looks like it was trying to update Heattrack in the logs but the reason for the failure is not clear! I'm opening an issue so we don't forget to investigate https://github.com/autamus/spacktainer-registry/runs/2086821841?check_suite_focus=true.

**Comment by alecbcs** [comment]
@vsoch should be fixed now! I realized that `repo_path` isn't actually the path of the containers but rather that of the git repository. Which should be the root directory for all actions. I'll append the Binoc docs to make this distinction.

**Comment by vsoch** [comment]
@alecbcs we just had another GitHub actions fail - should I disable them in this repository? We don't actually need it running here I think, and we can turn it on again if further testing is needed.

**Comment by vsoch** [comment]
okay disabled for now to limit the noise - we can turn on again if we want to continue developing or testing something here.

**Comment by alecbcs** [comment]
Oh yeah! Sorry I’d forgotten about the one in this repository. Good catch!
